# Generated by Django 5.0 on 2024-07-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
    ]
