name: Bicycle Sharing Actions
run-name: ${{ github.actor }} testing
on: [pull_request]
jobs:
  run_unittests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12']
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          echo "SECRET_KEY = 'django-insecure-dummy-secret'" >> ./.env
          echo -e "POSTGRES_DB = 'bicycle_db'" >> ./.env
          echo -e "POSTGRES_USER = 'bicycle'" >> ./.env
          echo -e "POSTGRES_PASSWORD = '12345'" >> ./.env
          python3 manage.py test








